name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    strategy:
      matrix:
        os:
          - os: ubuntu-latest
            tools:    apt perl python
            apt:      bmake
            perl:     App::ansiecho
            python:   legit
            ruby:     sinatra
          - os: macos-latest
            tools:    homebrew perl python
            homebrew: rcs
            perl:     App::ansiecho
            python:   legit
            ruby:     sinatra
    runs-on: ${{ matrix.os.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache:    workflow
          apt:      ${{ matrix.os.apt }}
          homebrew: ${{ matrix.os.homebrew }}
          perl:     ${{ matrix.os.perl }}
          python:   ${{ matrix.os.python }}
          ruby:     ${{ matrix.os.ruby }}
      - run: (cd __test__; ./run.sh ${{ matrix.os.tools }})
      - run: |
          : check cache-hit
          for tool in ${{ matrix.os.tools }}
          do
            case $tool in
              apt)      test "${{ steps.action.outputs.apt-cache-hit }}"      != true ;;
              homebrew) test "${{ steps.action.outputs.homebrew-cache-hit }}" != true ;;
              perl)     test "${{ steps.action.outputs.perl-cache-hit }}"     != true ;;
              python)   test "${{ steps.action.outputs.python-cache-hit }}"   != true ;;
              ruby)     test "${{ steps.action.outputs.ruby-cache-hit }}"     != true ;;
            esac
          done

  cached:
    needs: initial
    strategy:
      matrix:
        os:
          - os: ubuntu-latest
            tools:    apt perl python
            apt:      bmake
            perl:     App::ansiecho
            python:   legit
            ruby:     sinatra
          - os: macos-latest
            tools:    homebrew perl python
            homebrew: rcs
            perl:     App::ansiecho
            python:   legit
            ruby:     sinatra
    runs-on: ${{ matrix.os.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache:    workflow
          apt:      ${{ matrix.os.apt }}
          homebrew: ${{ matrix.os.homebrew }}
          perl:     ${{ matrix.os.perl }}
          python:   ${{ matrix.os.python }}
          ruby:     ${{ matrix.os.ruby }}
      - run: (cd __test__; ./run.sh ${{ matrix.os.tools }})
      - run: |
          : check cache-hit
          for tool in ${{ matrix.os.tools }}
          do
            case $tool in
              apt)      test "${{ steps.action.outputs.apt-cache-hit }}"      == true ;;
              homebrew) test "${{ steps.action.outputs.homebrew-cache-hit }}" == true ;;
              perl)     test "${{ steps.action.outputs.perl-cache-hit }}"     == true ;;
              python)   test "${{ steps.action.outputs.python-cache-hit }}"   == true ;;
              ruby)     test "${{ steps.action.outputs.ruby-cache-hit }}"     == true ;;
            esac
          done
